name: app_map_tracking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  maplibre_gl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/maplibre/
    - assets/maplibre/sprites/
    - assets/maplibre/glyphs/